#! /bin/bash
python3 bubble.py --train_dirs  /mnt/tmp/Bubble\ images/Dataset_1/test\#3\ 20ppm\ MIBC/Result\ \#\ 3\ 20ppm/  /mnt/tmp/Bubble\ images/Dataset_1/test\#4\ 20ppm\ MIBC/Result\ test\ \#\ 4\ 20ppm/ /mnt/tmp/Bubble\ images/Dataset_1/test\#6\ 20ppm\ MIBC/Result\ test\ \#\ 6\ 20ppm/ /mnt/tmp/Bubble\ images/Dataset_1/test\#7\ 20ppm\ MIBC/Result\ test\ \#\ 7\ 20ppm/ --val_dirs /mnt/tmp/Bubble\ images/Dataset_1/test\#8\ 20ppm\ MIBC/Result\ test\ \#\ 8\ 20ppm/ /mnt/tmp/Bubble\ images/Dataset_1/test\#9\ 20ppm\ MIBC/Result\ test\ \#\ 9\ 20ppm/ /mnt/tmp/Bubble\ images/Dataset_1/test\#10\ 20ppm\ MIBC/Result\ test\ \#\ 10\ 20ppm/ --weights imagenet --logs /mnt/tmp/logs_2018_07_02/


